language: php

php: [5.6, 7.0, 7.1]

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  
install:
  - composer install --no-interaction 

script:
 - composer ci
